export enum BlocksEnum {
	SAVE = 'Save',
	DISMISS = 'Dismiss',
    SEND_MESSAGE_LABEL = 'Send anyway',
    SEND_MESSAGE_ACTION_ID = 'send-message',
    SCHEDULE_MESSAGE_LABEL = 'Schedule',
    SCHEDULE_MESSAGE_ACTION_ID = 'schedule-message',
    CANCEL_MESSAGE_LABEL = 'Cancel',
    CANCEL_MESSAGE_ACTION_ID = 'cancel-message',
    CANCEL_SCHEDULE_LABEL = 'Cancel',
    CANCEL_SCHEDULE_ACTION_ID = 'cancel-schedule',
    TIMEOUT_MESSAGE = `:+1: I won\'t ask you again for the next %s minutes`,
    MESSAGE_CANCELLED = 'Your message is cancelled and won\'t be sent',
    MESSAGE_SCHEDULED = 'Your message has been scheduled for %s',
}
